# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import path
from . import views

admin.site.site_title = 'バイヤーズ 管理画面'
admin.site.site_header = 'バイヤーズ 管理画面'
admin.site.index_title = 'バイヤーズ メニュー'

app_name = 'yaget'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:num>', views.index, name='index'),
    path('test_mail/', views.test_mail, name='test_mail'),
    path('send_my_mail/', views.send_my_mail, name='send_my_mail'),
    path('showdetail/', views.showdetail, name='showdetail'),
    path('showdetail/<int:num>', views.showdetail, name='showdetail'),
    path('getdetail/', views.getdetail, name='getdetail'),
    path('getlist/', views.getlist, name='getlist'),
    path('addlist/', views.addlist, name='addlist'),
    path('set_list_to_sheet/', views.set_list_to_sheet, name='set_list_to_sheet'),
    path('read_s_sheet/', views.read_s_sheet, name='read_s_sheet'),
    path('kick_yaget/', views.kick_yaget, name='kick_yaget'),
    path('upd_byers_ct_list/', views.upd_byers_ct_list, name='upd_byers_ct_list'),
    path('upd_byers_ct_list_done/', views.upd_byers_ct_list_done, name='upd_byers_ct_list_done'),
    path('top/', views.top, name='top'),
    path('ajax_test/', views.ajax_test, name='ajax_test'),
    path('ajax_test_add/', views.ajax_test_add, name='ajax_test_add'),
    path('buyers_goods_detail_ajax_res/', views.buyers_goods_detail_ajax_res,
         name='buyers_goods_detail_ajax_res'),
    path('qoo_goods_upsert_ajax/', views.qoo_goods_upsert_ajax,
         name='qoo_goods_upsert_ajax'),
    path('qoo_goods_detail_info_ajax/', views.qoo_goods_detail_info_ajax,
         name='qoo_goods_detail_info_ajax'),
    path('qoo10_cert_test/', views.qoo10_cert_test,
         name='qoo10_cert_test'),
    path('stock_chk/', views.stock_chk,
         name='stock_chk'),
    path('qoo_get_order_info_ajax_res/', views.qoo_get_order_info_ajax_res,
         name='qoo_get_order_info_ajax_res'),
    path('wow_goods_upsert_ajax/', views.wow_goods_upsert_ajax,
         name='wow_goods_upsert_ajax'),
    path('wow_get_order_info_ajax_res/', views.wow_get_order_info_ajax_res,
         name='wow_get_order_info_ajax_res'),
    path('buyers_goods_detail_export/', views.BuyersGoodsDetailExport, name='buyers_goods_detail_export'),
    path('buyers_goods_detail_import/', views.BuyersGoodsDetailImport.as_view(), name='buyers_goods_detail_import'),
    path('buyers_goods_detail_s_export/', views.BuyersGoodsDetailSmallExport, name='buyers_goods_detail_s_export'),
    path('buyers_goods_detail_s_import/', views.BuyersGoodsDetailSmallImport.as_view(), name='buyers_goods_detail_s_import'),
    path('buyers_goods_delete/', views.BuyersGoodsDelete.as_view(), name='buyers_goods_delete'),
    path('buyers_goods_delete_confirm/', views.BuyersGoodsDeleteConfirm, name='buyers_goods_delete_confirm'),
    path('buyers_goods_delete_done/', views.buyers_goods_delete_done, name='buyers_goods_delete_done'),
    path('buyers_goods_detail_list/', views.BuyersGoodsDetailList.as_view(),
         name='buyers_goods_detail_list'),
    path('<pk>/buyers_goods_detail_detail/', views.BuyersGoodsDetailDetail.as_view(),
         name='buyers_goods_detail_detail'),
    path('<pk>/buyers_goods_detail_update/', views.BuyersGoodsDetailUpdate.as_view(),
         name='buyers_goods_detail_update'),
    path('<pk>/buyers_goods_detail_delete/', views.BuyersGoodsDetailDelete.as_view(),
         name='buyers_goods_detail_delete'),
    path('batch_status_list/', views.BatchStatusList.as_view(),
         name='batch_status_list'),
    path('<pk>/batch_status_detail/', views.BatchStatusDetail.as_view(),
         name='batch_status_detail'),
    path('<pk>/batch_status_delete/', views.BatchStatusDelete.as_view(),
         name='batch_status_delete'),
    path('black_list_list/', views.BlackListList.as_view(),
         name='black_list_list'),
    path('wowma_cat_list/', views.WowmaCatList.as_view(),
         name='wowma_cat_list'),
    path('<pk>/wowma_cat_detail/', views.WowmaCatDetail.as_view(),
         name='wowma_cat_detail'),
    path('<pk>/wowma_cat_update/', views.WowmaCatUpdate.as_view(),
         name='wowma_cat_update'),
    path('wowma_cat_model_list/', views.WowmaCatModelList.as_view(),
         name='wowma_cat_model_list'),
    path('<pk>/black_list_detail/', views.BlackListDetail.as_view(),
         name='black_list_detail'),
    path('<pk>/black_list_delete/', views.BlackListDelete.as_view(),
         name='black_list_delete'),
    path('black_list_create/', views.BlackListCreate.as_view(),
         name='black_list_create'),
    path('qoo_shop_info_list/', views.QooShopInfoList.as_view(),
         name='qoo_shop_info_list'),
    path('<pk>/qoo_shop_info_detail/', views.QooShopInfoDetail.as_view(),
         name='qoo_shop_info_detail'),
    path('<pk>/qoo_shop_info_delete/', views.QooShopInfoDelete.as_view(),
         name='qoo_shop_info_delete'),
    path('qoo_shop_info_create/', views.QooShopInfoCreate.as_view(),
         name='qoo_shop_info_create'),
    path('<pk>/qoo_shop_info_update/', views.QooShopInfoUpdate.as_view(),
         name='qoo_shop_info_update'),
    path('wow_shop_info_list/', views.WowShopInfoList.as_view(),
         name='wow_shop_info_list'),
    path('<pk>/wow_shop_info_detail/', views.WowShopInfoDetail.as_view(),
         name='wow_shop_info_detail'),
    path('<pk>/wow_shop_info_delete/', views.WowShopInfoDelete.as_view(),
         name='wow_shop_info_delete'),
    path('wow_shop_info_create/', views.WowShopInfoCreate.as_view(),
         name='wow_shop_info_create'),
    path('<pk>/wow_shop_info_update/', views.WowShopInfoUpdate.as_view(),
         name='wow_shop_info_update'),
    path('error_goods_log_list/', views.ErrorGoodsLogList.as_view(),
         name='error_goods_log_list'),
    path('<pk>/error_goods_log_detail/', views.ErrorGoodsLogDetail.as_view(),
         name='error_goods_log_detail'),
    path('<pk>/error_goods_log_delete/', views.ErrorGoodsLogDelete.as_view(),
         name='error_goods_log_delete'),
    path('all_order_list/', views.AllOrderList.as_view(),
         name='all_order_list'),
    path('qoo_order_list/', views.QooOrderList.as_view(),
         name='qoo_order_list'),
    path('<pk>/qoo_order_detail/', views.QooOrderDetail.as_view(),
         name='qoo_order_detail'),
    path('<pk>/qoo_order_update/', views.QooOrderUpdate.as_view(),
         name='qoo_order_update'),
    path('<pk>/qoo_order_delete/', views.QooOrderDelete.as_view(),
         name='qoo_order_delete'),
    path('wow_order_list/', views.WowOrderList.as_view(),
         name='wow_order_list'),
    path('<pk>/wow_order_detail/', views.WowOrderDetail.as_view(),
         name='wow_order_detail'),
    path('<pk>/wow_order_update/', views.WowOrderUpdate.as_view(),
         name='wow_order_update'),
    path('<pk>/wow_order_delete/', views.WowOrderDelete.as_view(),
         name='wow_order_delete'),
    path('qoo_order_seller_chk_ajax_res/', views.qoo_order_seller_chk_ajax_res,
         name='qoo_order_seller_chk_ajax_res'),
    path('qoo_order_sending_info_ajax/', views.qoo_order_sending_info_ajax,
         name='qoo_order_sending_info_ajax'),
    path('qoo_do_order_buyers_ajax/', views.qoo_do_order_buyers_ajax,
         name='qoo_do_order_buyers_ajax'),
    path('wow_order_seller_chk_ajax_res/', views.wow_order_seller_chk_ajax_res,
         name='wow_order_seller_chk_ajax_res'),
    path('wow_order_sending_info_ajax/', views.wow_order_sending_info_ajax,
         name='wow_order_sending_info_ajax'),
    path('wow_do_order_buyers_ajax/', views.wow_do_order_buyers_ajax,
         name='wow_do_order_buyers_ajax'),
    path('wow_send_gmail_ajax/', views.wow_send_gmail_ajax,
         name='wow_send_gmail_ajax'),
    path('qoo_asin_detail_list/', views.QooAsinDetailList.as_view(),
         name='qoo_asin_detail_list'),
    path('<int:pk>/qoo_asin_detail_detail/', views.QooAsinDetailDetail.as_view(),
         name='qoo_asin_detail_detail'),
    path('<int:pk>/qoo_asin_detail_update/', views.QooAsinDetailUpdate.as_view(),
         name='qoo_asin_detail_update'),
    path('<int:pk>/qoo_asin_detail_delete/', views.QooAsinDetailDelete.as_view(),
         name='qoo_asin_detail_delete'),
    path('qoo_asin_csv_export/', views.QooAsinCsvExport, name='qoo_asin_csv_export'),
    path('qoo_asin_csv_import/', views.QooAsinCsvImport.as_view(), name='qoo_asin_csv_import'),
    path('get_qoo_asin_detail_single/', views.get_qoo_asin_detail_single, name='get_qoo_asin_detail_single'),
    path('get_qoo_asin_detail_upd_csv/', views.get_qoo_asin_detail_upd_csv, name='get_qoo_asin_detail_upd_csv'),
]
