# Generated by Django 3.2.9 on 2023-02-13 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yaget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowCategory',
            fields=[
                ('product_cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_cat_name', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('level_1_cat_name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('level_2_cat_name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('level_3_cat_name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('level_4_cat_name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('ama_level_1_cat_id', models.IntegerField(blank=True, default=0, null=True)),
                ('ama_level_2_cat_id', models.IntegerField(blank=True, default=0, null=True)),
                ('ama_level_3_cat_id', models.IntegerField(blank=True, default=0, null=True)),
                ('ama_level_1_cat_name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('ama_level_2_cat_name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('ama_level_3_cat_name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='amacategory',
            old_name='parent_ca_id',
            new_name='level_1_cat_name',
        ),
        migrations.AddField(
            model_name='amacategory',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_1_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_2_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_2_cat_name',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_3_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_3_cat_name',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_4_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_4_cat_name',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_5_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_5_cat_name',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_6_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_6_cat_name',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_7_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_7_cat_name',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_8_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='level_8_cat_name',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='parent_cat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amacategory',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='qoocategory',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qoocategory',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='amacategory',
            name='product_cat_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
