# Generated by Django 3.2.9 on 2026-04-18 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yaget', '0003_lwacredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowmaShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_user_id', models.CharField(db_index=True, max_length=20)),
                ('wow_item_id', models.CharField(max_length=20, unique=True)),
                ('item_name', models.TextField()),
                ('item_url', models.URLField(max_length=512)),
                ('asin', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('asin_name', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='wowmashopitem',
            index=models.Index(fields=['shop_user_id', 'status'], name='yaget_wowma_shop_us_11288d_idx'),
        ),
    ]
