# Generated by Django 3.2.9 on 2026-04-19 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yaget', '0004_auto_20260419_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bullet_points', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('main_image_url', models.URLField(blank=True, max_length=600)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_rank', models.IntegerField(blank=True, null=True)),
                ('sales_rank_category', models.CharField(blank=True, max_length=255)),
                ('is_discontinued', models.BooleanField(blank=True, null=True)),
                ('has_fba_offer', models.BooleanField(blank=True, null=True)),
                ('is_sold_by_amazon', models.BooleanField(blank=True, null=True)),
                ('fba_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fba_shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fba_ship_min_hours', models.IntegerField(blank=True, null=True)),
                ('fba_ship_max_hours', models.IntegerField(blank=True, null=True)),
                ('availability_type', models.CharField(blank=True, max_length=20)),
                ('available_date', models.DateTimeField(blank=True, null=True)),
                ('is_preorder', models.BooleanField(blank=True, null=True)),
                ('is_prime', models.BooleanField(blank=True, null=True)),
                ('fba_is_buybox_winner', models.BooleanField(blank=True, null=True)),
                ('fba_offer_count', models.IntegerField(blank=True, null=True)),
                ('merchant_offer_count', models.IntegerField(blank=True, null=True)),
                ('has_quantity_discount', models.BooleanField(blank=True, null=True)),
                ('offers_raw', models.TextField(blank=True)),
                ('is_listable', models.BooleanField(blank=True, null=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offers_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Amazon商品詳細',
                'verbose_name_plural': 'Amazon商品詳細',
            },
        ),
        migrations.AddField(
            model_name='wowmashopitem',
            name='amazon_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wowma_items', to='yaget.amazonitemdetail'),
        ),
    ]
